FROM python:3.10.0 as python-base

ARG APP_NAME = app
ARG APP_PATH = /$APP_NAME
ARG POETRY_VERSION=1.4.2

ENV \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONFAULTHANDLER=1
ENV \
    POETRY_VERSION=$POETRY_VERSION \
    POETRY_HOME="/$APP_NAME/poetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_NO_INTERACTION=1

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="$POETRY_HOME/bin:$PATH"
RUN echo $POETRY_HOME

#RUN pip --no-cache-dir install poetry==1.4.2

WORKDIR $APP_PATH
COPY pyproject.toml ./
COPY poetry.lock ./

RUN poetry install

COPY ./ ./

#RUN source $(poetry env info --path)/bin/activate
#ENTRYPOINT poetry run python ./main.py