FROM python:3.10.0-alpine

WORKDIR /usr/src/app  # /usr/src/app으로 이동

COPY requirements.txt .  # requirements.txt 복사

RUN pip install --no-cache-dir -r requirements.txt  # requirements.txt 내용 실행
COPY . .

EXPOSE 80

CMD ["python", "./api/main.py"]