version: "3.8"

services:
  fast_api:
    image: python:3.10.0-alpine
    build:
      context: .
    restart: always
    volumes:
      - ./:/app/
    networks:
      - network_backend
    ports:
      - "80:80"
    env_file:
      - ./.env

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    networks:
      - network_backend
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: 'backend'
        MYSQL_ROOT_PASSWORD: '1234'
    expose:
        - "3306"
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
#    environment:
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:1234}
#      - MYSQL_DATABASE=${MYSQL_DATABASE:backend}

networks:
  network_backend:
      driver: bridge