FROM python:3.10.0-alpine

#mysql dependencies

RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add --no-cache mariadb-dev\
    && apk del build-deps

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /app

RUN pip install poetry==1.4.2

COPY pyproject.toml /app/
COPY poetry.lock /app/

RUN poetry config virtualenvs.create false
#RUN poetry env use python3
RUN poetry install --without dev && rm -rf $POETRY_CACHE_DIR

COPY . /app

#RUN poetry install --without dev

ENTRYPOINT ["poetry", "run", "python3", "-m", "/app/api/main"]