version: "3"

services:
  fast_api:
#    image: python:3.10.0-alpine
    build:
      context: .
      dockerfile: Dockerfile.txt
    restart: always
    volumes:
      - ./:/app/
    networks:
      - network_backend
    ports:
      - "80:80"
    command: ["chmod", "+x", "/app/*.sh"]
#    env_file:
#      - ./.env
#  entrypoint:
#    - sh
#    - config/docker/entrypoint.prod.sh

#  nginx: # 컨테이너2 : nginx
#    container_name: nginx
#    build: ./config/nginx
#    volumes:
#      - static:/home/app/web/static
#      - media:/home/app/web/media
#    ports:
#      - "80:80"
#    depends_on:
#      - fast_api

  mysql:
    image: mysql:5.7
    restart: always
#    build:
#      context: /db
#      dockerfile: Dockerfile_db.txt
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    networks:
      - network_backend
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: 'backend'
        MYSQL_ROOT_PASSWORD: '1234'
    expose:
        - "3306"
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
#    environment:
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:1234}
#      - MYSQL_DATABASE=${MYSQL_DATABASE:backend}

networks:
  network_backend:
      driver: bridge