# vim Dcokerfile_mariaDB_01

FROM mariadb:10.2.38 # mysql 5.7 compatible

ENV MYSQL_ROOT_PASSWORD=1234  # root pw 설정

ENV MYSQL_DATABASE=backend  # 생성할 DB 이름 설정

ENV MYSQL_USER=user  # user 생성

ENV MYSQL_PASSWORD=1234  # user pw 생성

COPY my.cnf /etc/mysql/my.cnf  # my.cnf의 설정내용 복사

EXPOSE 3000  # port 3000번으로 설정

CMD ["mysqld"]  # 명령어 mysqld 사용